name: tell everyone about bun

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -s -X POST -H "Content-Type: application/json" -d '{"content": "have you guys seen https://bun.sh/ ? Looks promising...."}' "$WEBHOOK_URL"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
